### PR TITLE
Leap Year Program of Python

### PR DESCRIPTION
**Pull request by Anujmishra2005**
# Pull Request

 

## Description:

 This is Leap Year Program of Python 

## Related Issue:

Closes #XXXXX

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
This pull request is not related to this repository at all. You are adding a python file to a JavaScript project.

We are marking this pull request as spam. Please note that if you are participating in Hacktoberfest, two or more PRs marked as spam will result in your permanent disqualification.

If you are interested in making quality and genuine contributions to our projects, check out our [open issues](https://contribute.naomi.lgbt).

**Comment by Anujmishra2005** [comment]
Sorry But I am not aware of this kind of thing but it is very rude
behaviour of yours that you have made my file spam . Man just firstly think
about your actions and then do . Your one wrong step can ruin everything .

**Comment by naomi-lgbt** [comment]
...
You added a python file to our .github folder. It serves 0 purpose. It is not a valid contribution.

**Comment by Anujmishra2005** [comment]
I have Added python file you can simply message me but you  have spammed my
file and not understand what I am trying to do . Bro this is very rude
behaviour from my side you can simply reject it but you have not done that

**Comment by naomi-lgbt** [comment]
I'm not sure *you* understand what you're trying to do. Where, in ANY of our contribution guidelines, does it say to add python files to the . github folder??

If you are interest in legitimate contribution, we would love to help you in our [discord server](https://chat.nhcarrigan.com).

**Comment by KyleTryon** [comment]
@Anujmishra2005 When you submit a "junk" PR in the pursuit of a free t-shirt, which adds no value to the code base, you are causing real people real time (and therefore money) who have to sift through this, review it, and decide if it is helpful or not. 

Please do not inconvenience repository maintainers and developers by submitting spam.

I highly recommend taking a look at the following resources:

- [How to contribute to open source](https://opensource.guide/how-to-contribute)
- [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)
 I _highly_ recommend looking for existing open issues that you can _resolve_ by opening a PR. There is a huge list available here: https://github.com/topics/hacktoberfest
You can click this link and even filter down to the language you want to contribute to.

Please remember to be considerate to the maintainers of these projects, and do not submit spam PRs.

**Comment by naomi-lgbt** [comment]
image

**Comment by krshkun** [comment]
@Anujmishra2005 I don't think this is appropriate behaviour as a contributor, I am also a contributor to open source but behaving like this to maintainers has never been a thing with me or any other people I know

I would like to point out:

1. Making pull requests that don't add any value take up valuable time as mentioned by @KyleTryon and for your very very highly sophisticated englisb dictionary, spam is anything message or action that annoys and wastes the time of others. Justified why it is spam
2. Your code is not useless because of what it is (but it is still useless because of your attitude) but because it serves no use to the project
3. You won't get any free t-shirts by spamming prs, so please find a job 😀
4. I think even you know that your PR is a piece of garbage and just for the free t-shirt.

This rudeness doesn't have place in the open source community, therefore reporting you

**Pull request closed without merging**
